# Get Data

In [292]:
import nltk
nltk.download('punkt')
import math
import pandas as pd

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/BakerStreetBakery/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [293]:
text = pd.read_csv('./data/Full-Economic-News-DFE-839861.csv')
print 'total number of articles', len(text)
articles_to_use = 200

total number of articles 8000


In [326]:
articles = [x.replace('</br>', ' ') for x in text['text'][:articles_to_use]]
all_articles = []
for a in articles:
    tokens = nltk.word_tokenize(a)
    all_articles.append([word.lower() for word in tokens if word.isalpha()])
    
total_tokens = nltk.word_tokenize(' '.join(articles))
all_words = [word.lower() for word in total_tokens if word.isalpha()]

print all_words[:150]
print articles[:1]
print '\ntotal number of words:', len(all_words)

['new', 'york', 'yields', 'on', 'most', 'certificates', 'of', 'deposit', 'offered', 'by', 'major', 'banks', 'dropped', 'more', 'than', 'a', 'tenth', 'of', 'a', 'percentage', 'point', 'in', 'the', 'latest', 'week', 'reflecting', 'the', 'overall', 'decline', 'in', 'interest', 'rates', 'on', 'or', 'consumer', 'cds', 'sold', 'directly', 'by', 'banks', 'the', 'average', 'yield', 'on', 'deposits', 'fell', 'to', 'from', 'in', 'the', 'week', 'ended', 'yesterday', 'according', 'to', 'an', 'survey', 'by', 'banxquote', 'money', 'markets', 'a', 'wilmington', 'information', 'service', 'on', 'consumer', 'deposits', 'the', 'average', 'yield', 'sank', 'to', 'from', 'the', 'week', 'before', 'according', 'to', 'banxquote', 'two', 'banks', 'in', 'the', 'banxquote', 'survey', 'citibank', 'in', 'new', 'york', 'and', 'corestates', 'in', 'pennsylvania', 'are', 'paying', 'less', 'than', 'on', 'threemonth', 'cds', 'declines', 'were', 'somewhat', 'smaller', 'on', 'consumer', 'cds', 'which', 'eased', 'to', 'from

# Raw Frequency

In [327]:
min_threshold_tau = 5
words_len = len(all_words)

In [328]:
f = {}
index = {}
for i in range(words_len):
    word = all_words[i]
    if word not in index.keys():
        index[word] = [i]
    else:
        index[word].append(i)


In [329]:
print 'sample words found:', index.keys()[:10]
print 'sample frequency:', index[index.keys()[3]]

sample words found: ['four', 'mirage', 'adjustors', 'increase', 'eligible', 'electricity', 'sinking', 'regional', 'bringing', 'scholar']
sample frequency: [3073, 3943, 4385, 4544, 4637, 6566, 7259, 9210, 10490, 12659, 14185, 14272, 15537, 17272, 17905, 19344, 19753, 20922, 22247, 23219, 23826, 23871, 26225, 26915, 27180, 29750, 29799, 30016, 30540, 31554, 32068, 32082, 32132, 32959, 34327, 37354, 37420, 38332, 40072, 42306]


In [330]:
index_allwords = index.copy()
index_allwords['risen']

[12647, 35904, 36094, 37721, 43154]

In [331]:
while len(index.keys()) > 0:
    index_p = {}
    for j in index.keys():
        if len(index[j]) >= min_threshold_tau:
            f[j] = len(index[j])
            for k in index[j]:
                if k+1 < words_len:
                    new_phrase = j + u' ' + all_words[k + 1]
                    if new_phrase not in index_p.keys():
                        index_p[new_phrase] = [k + 1]
                    else:
                        index_p[new_phrase].append(k + 1)
    index = index_p
    print index.keys()[:10]

[u'rate raising', u'is nestled', u'settlement mci', u'and pray', u'also was', u'foreign currency', u'index measure', u'open new', u'at georgetown', u'yield that']
[u'to be cut', u'a year what', u'from the company', u'known as quantitative', u'whether the high', u'after a good', u'federal reserve from', u'months ago raising', u'the nasdaq composition', u'according to banxquote']
[u'over the past three', u'new york the dollar', u'the economy has started', u'the federal reserve has', u'the stock market that', u'a annual rate perhaps', u'one of the quintessential', u'in the dollar value', u'the wall street journal', u'a year earlier royal']
[u'is expected to be even', u'new york stock exchange already', u'in the stock market where', u'dow jones industrial average lost', u'in the fourth quarter by', u'the nasdaq composite index eased', u'more than a year and', u'the standard poor index edged', u'the nasdaq composite index gained', u'the nasdaq stock market and']
[u'the dow jones industrial 

In [332]:
print 'total phrases above threshold:', len(f.keys())
print 'sample phrases:', f.keys()[:10]

total phrases above threshold: 2272
sample phrases: ['limited', u'an annual', u'the second', u'the most', u'to and the', u'new york stock exchange', 'four', u'unemployment rate', 'asian', u'the last']


In [333]:
f.keys()

['limited',
 u'an annual',
 u'the second',
 u'the most',
 u'to and the',
 u'new york stock exchange',
 'four',
 u'unemployment rate',
 'asian',
 u'the last',
 'increase',
 u'the president',
 'voted',
 'under',
 u'a seasonally',
 u'and interest',
 'worth',
 'rescue',
 'rise',
 u'will make',
 'every',
 'reforms',
 'affect',
 'school',
 u'the number of',
 'prize',
 u'a annual rate',
 'companies',
 'wednesday',
 'red',
 u'against the',
 'bernanke',
 'force',
 'leaders',
 u'managing director',
 'estimates',
 'japanese',
 u'because of',
 'second',
 'persuade',
 'estimated',
 u'the recession',
 'machines',
 'even',
 u'year earlier',
 u'is it',
 'asia',
 'spokesman',
 u'they had',
 u'the fall',
 'above',
 'new',
 'net',
 'ever',
 'told',
 u'a gain',
 u'and it',
 u'lower interest',
 'whose',
 u'in many',
 'never',
 u'or to and',
 'here',
 'reported',
 'protection',
 'china',
 u'and in',
 u'compared to',
 u'starting to',
 'auction',
 'study',
 'climbed',
 'reports',
 'credit',
 'analysts',
 'cha

# Quality Score

In [334]:
phrases = []
for w in f.keys():
    if len(w.split(u' ')) > 1:
        phrases.append(w)

In [335]:
print 'total 2 words and above phrases:', len(phrases)
print 'sample:', phrases[:10]

total 2 words and above phrases: 972
sample: [u'an annual', u'the second', u'the most', u'to and the', u'new york stock exchange', u'unemployment rate', u'the last', u'the president', u'a seasonally', u'and interest']


# Concordance

In [336]:
PMI = {}
PLK = {}

In [337]:
def prob_u(phrase, f):
    words = phrase.split(u' ')
    denom = 0
    for j in words:
        denom += f[word]
    return f[phrase]*1. / denom

In [338]:
def cal_PMI_PLK(phrase, f, pmi, plk):
    words = phrase.split(u' ')
    prob_whole = prob_u(phrase, f)
    if len(words) > 2:
        min_mutual_info = float('inf')
        best_u_left = None
        best_u_right = None
        for i in range(1, len(words)):
            u_left = u' '.join(words[:i])
            u_right = u' '.join(words[i:])
            info = math.log(prob_whole * 1. / (prob_u(u_left, f) * prob_u(u_right, f)))
            if info < min_mutual_info:
                min_mutual_info = info
                best_u_left = u_left
                best_u_right = u_right
    else:
        best_u_left = words[0]
        best_u_right = words[1]
    
    pmi[phrase] = math.log(prob_whole * 1. / (prob_u(best_u_left, f) * prob_u(best_u_right, f)))
    plk[phrase] = prob_whole * math.log(prob_whole * 1. / (prob_u(best_u_left, f) * prob_u(best_u_right, f)))


In [339]:
for p in phrases:
    cal_PMI_PLK(p, f, PMI, PLK)

In [340]:
print len(PMI.keys())
print PMI.keys()[:10]
print PMI[PMI.keys()[0]]
print PLK[PLK.keys()[0]]

972
[u'last month', u'a record', u'to say', u'second quarter', u'an annual', u'to have', u'the second', u'the most', u'the wall street', u'unemployment rate for']
-4.31255287835
-11.2126374837


# Informativeness

In [341]:
IDF_phrase = {}
IDF_word = {}


In [342]:
print 'total articles:', len(articles)


total articles: 200


In [343]:
def cal_word_IDF(docs, idf_word):
    total_length = len(docs)
    for w in all_words:
        count = 0
        for d in docs:
            if w in d:
                count += 1
        if count > 0:
            idf_word[w] = math.log(total_length * 1. / count)
        else:
            idf_word[w] = 0
        
        

In [344]:
cal_word_IDF(all_articles, IDF_word)

In [345]:
print IDF_word.keys()[:5]
index = IDF_word.keys()[:5]
for i in index:
    print IDF_word[i]

['four', 'mirage', 'adjustors', 'increase', 'eligible']
2.20727491319
5.29831736655
5.29831736655
1.83258146375
4.19970507788


In [346]:
def cal_phrase_IDF(phrases, word_idf, phrase_idf):
    for p in phrases:
        idf = 0
        words = p.split(u' ')
        for w in words:
            idf += word_idf[w]
        phrase_idf[p] = idf * 1. / len(words)

In [347]:
cal_phrase_IDF(phrases, IDF_word, IDF_phrase)

In [349]:
print IDF_phrase.keys()[:10]
for p in IDF_phrase.keys()[:10]:
    print IDF_phrase[p]

[u'last month', u'a record', u'to say', u'second quarter', u'an annual', u'to have', u'the second', u'the most', u'the wall street', u'unemployment rate for']
1.39233065174
1.22699477358
0.939721899936
2.08669388478
1.46403681254
0.301950401523
1.10614372751
0.70575480513
1.58894551262
1.36355710562


# Train Classifier

In [350]:
data = {}
for p in phrases:
    data[p] = []
    data[p].append(float(PMI[p]))
    data[p].append(float(PLK[p]))
    data[p].append(float(IDF_phrase[p]))


In [351]:
import numpy as np
import sklearn

In [352]:
print(data.keys())

[u'last month', u'a record', u'to say', u'second quarter', u'an annual', u'to have', u'the second', u'the most', u'the wall street', u'unemployment rate for', u'to give', u'unemployment rate', u'chairman of', u'in what', u'the last', u'trade deficit', u'companies that', u'million or cents a', u'continues to', u'a increase', u'meanwhile the', u'said in', u'sign that', u'said it', u'the president', u'of in', u'ability to', u'is no', u'a seasonally', u'and interest', u'dow jones industrial average', u'much of', u'bush administration', u'years ago', u'warburg pincus', u'will make', u'funds and', u'fed officials', u'they were', u'is still', u'financial crisis', u'more than of', u'than a', u'fed chairman', u'over the', u'to and', u'treasury secretary', u'show that', u'york a', u'against the', u'york stock exchange', u'up from', u'wall street', u'due to', u'the global', u'or to the', u'stocks rose', u'when he', u'year according', u'declined to', u'of all', u'the cftc', u'that are', u'the rece

In [353]:
qual_phrase = [u'dow jones industrial average', 
              u'chairman ben bernanke', 
              u'economic recovery',
              u'business investment', 
              u'nasdaq composite index', 
              u'commerce department', 
              u'interest rates', 
             u'seasonally adjusted', 
              u'labor department', 
              u'central banks']
rand_phrase = [u'to billion',
              u'and new',
              u'but it is',
              u'starting to', 
              u'if we',
              u'year and', 
              u'said in',
              u'rise in',
              u'or to the',
              u'professor at']

In [354]:
train_data = []
for j in qual_phrase:
        train_data.append([1] + data[j])

for j in rand_phrase:
        train_data.append([0] + data[j])
train_data = np.array(train_data)
np.random.shuffle(train_data)

In [361]:
print(train_data.shape)
X = train_data[:, 1:]
y = train_data[:, 0]
print X.shape
print y.shape
print train_data[:10]

(20, 4)
(20, 3)
(20,)
[[  0.          -7.07898996  -9.20268695   0.97420664]
 [  0.          -5.4672159   -2.73360795   2.0227772 ]
 [  0.          -8.03835707 -12.05753561   0.79992947]
 [  1.          -4.05352257 -31.21212377   1.18757789]
 [  1.          -2.31055326  -0.77018442   3.05385007]
 [  1.          -1.38629436  -0.97040605   3.22675   ]
 [  1.          -4.76217393  -2.85730436   2.06137202]
 [  0.          -9.38438779  -4.6921939    0.38739558]
 [  1.          -3.33220451  -6.33118857   2.23270412]
 [  0.          -8.46005125  -5.64003417   0.26194802]]


In [356]:
test_data = []
test_phrases = []
for p in phrases:
    if p not in qual_phrase and p not in rand_phrase:
        test_data.append(data[p])
        test_phrases.append(p)
test_data = np.array(test_data)
print test_data

[[ -5.9176027   -2.95880135   1.46403681]
 [ -7.38013109 -14.76026218   1.10614373]
 [ -8.26719219 -14.88094593   0.70575481]
 ..., 
 [ -5.76957022  -3.84638014   1.07744386]
 [ -9.29922998  -9.29922998   0.71606445]
 [ -9.10817475  -4.55408737   1.08391785]]


In [362]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(max_depth=3, n_estimators=10,random_state=0)
clf.fit(X, y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=3, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=1, oob_score=False, random_state=0,
            verbose=0, warm_start=False)

In [364]:
predictions = []
pred_data = clf.predict_proba(test_data)
for k in range(len(test_data)):
    predictions.append([test_phrases[k], pred_data[k][1]])
print(predictions[:10])

[[u'an annual', 0.19], [u'the second', 0.14999999999999999], [u'the most', 0.0], [u'to and the', 0.13999999999999999], [u'new york stock exchange', 0.76000000000000001], [u'unemployment rate', 0.77500000000000002], [u'the last', 0.0], [u'the president', 0.13500000000000001], [u'a seasonally', 0.19], [u'and interest', 0.025000000000000001]]


In [366]:
best_predictions = []
worst_predictions = []
for p in predictions:
    if p[1] >= 0.8:
        best_predictions.append(p)
    elif p[1] < 0.2:
        worst_predictions.append(p)
print 'best predictions:', best_predictions[:10]
print 'worst predictions:', worst_predictions[:10]

best predictions: [[u'managing director', 1.0], [u'central bank', 0.84999999999999998], [u'price increases', 0.90000000000000002], [u'ben bernanke', 1.0], [u'policy makers', 1.0], [u'royal bank', 0.90000000000000002], [u'budget deficit', 0.90000000000000002], [u'their bills', 0.90000000000000002], [u'vice president', 0.98000000000000009], [u'familiar with', 0.90000000000000002]]
worst predictions: [[u'an annual', 0.19], [u'the second', 0.14999999999999999], [u'the most', 0.0], [u'to and the', 0.13999999999999999], [u'the last', 0.0], [u'the president', 0.13500000000000001], [u'a seasonally', 0.19], [u'and interest', 0.025000000000000001], [u'a annual rate', 0.11000000000000001], [u'against the', 0.050000000000000003]]
